# fly.toml app configuration file generated for billowing-water-2310 on 2023-07-05T15:44:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-water-2310"
primary_region = "yyz"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
